CompanyName/CompanyName.AppName.Web/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompanyName.AppName.Domain.Entities;
using CompanyName.AppName.Web.Extensions;
using CompanyName.AppName.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Reusable.Business.Core.BusinessResult;

namespace CompanyName.AppName.Web.Controllers
{
    //[Route("[controller/[action]")]
    public class ActivityController : Controller
    {
        private readonly ActivityApiService _activityApiService;

        public ActivityController(ActivityApiService activityApiService)
        {
            _activityApiService = activityApiService;
        }

        public async Task<IActionResult> Index(string term)
        {
            List<Activity> model = new List<Activity>();

            return View(model);
        }


        [HttpGet]
        public Task<IActionResult> Create()
        {
            return Task.Run(() =>
            {
                return View() as IActionResult;
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Activity activite)
        {
            BusinessResult businessResult;

            if (ModelState.IsValid)
            {
                businessResult = await _activityApiService.PostAsync(activite);

                if (businessResult.Succeeded)
                {
                    TempData["Message"] = businessResult.ToBootstrapAlerts();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["Message"] = businessResult.ToBootstrapAlerts();
                }
            }

            return View(activite);
        }


        //[HttpGet("{id}")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Activity activity = await _activityApiService.GetByIdAsync(id);
            return View(activity);
        }

        [ValidateAntiForgeryToken]
        //[HttpPost("{id}")]
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, Activity activity)
        {
            BusinessResult businessResult;
            if (ModelState.IsValid)
            {
                businessResult = await _activityApiService.PutAsync(id, activity);

                if (businessResult.Succeeded)
                {
                    TempData["Message"] = businessResult.ToBootstrapAlerts();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["Message"] = businessResult.ToBootstrapAlerts();
                }
            }

            return View(activity);
        }

        //[HttpGet("{id}")]
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            Activity activity = await _activityApiService.GetByIdAsync(id);
            return View(activity);
        }
        [ValidateAntiForgeryToken]
        //[HttpPost("{id}")]
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id, Activity activity)
        {
            BusinessResult businessResult;
            businessResult = await _activityApiService.DeleteAsync(id, activity);

            if (businessResult.Succeeded)
            {
                TempData["Message"] = businessResult.ToBootstrapAlerts();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["Message"] = businessResult.ToBootstrapAlerts();
            }

            return View(activity);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            Activity activity = await _activityApiService.GetByIdAsync(id);
            return View(activity);
        }
    }
}

CompanyName/CompanyName.AppName.Web/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompanyName.AppName.Business;
using CompanyName.AppName.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace CompanyName.AppName.Web.Controllers
{
    public class CityController : GenericReferentielController<City, Guid>
    {
        private readonly ReferentielBusinessService<State, Guid> _wilayaBusinessService;
        public CityController(ReferentielBusinessService<City, Guid> communeBusinessService, ReferentielBusinessService<State, Guid> wilayaBusinessService) :base(communeBusinessService)
        {
            _wilayaBusinessService = wilayaBusinessService;
        }
       
    }
}

CompanyName/CompanyName.AppName.Web/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompanyName.AppName.Business;
using CompanyName.AppName.Domain.Entities;
using CompanyName.AppName.Web.Extensions;
using Microsoft.AspNetCore.Mvc;
using Reusable.Business.Core.BusinessResult;

namespace CompanyName.AppName.Web.Controllers
{
    public class PersonController : Controller
    {

        protected readonly PersonBusinessService _personBusinessService;

        public PersonController(PersonBusinessService personBusinessService)
        {
            _personBusinessService = personBusinessService;
        }

        public IActionResult Index()
        {
            return View(_personBusinessService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            BusinessResult businessResult;
            if (ModelState.IsValid)
            {
                businessResult = _personBusinessService.Add(person);
                if (businessResult.Succeeded)
                {
                    TempData["Message"] = businessResult.ToBootstrapAlerts();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["Message"] = businessResult.ToBootstrapAlerts();
                }
            }
            return View(person);
        }


        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var person = _personBusinessService.GetById(id);
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, Person person)
        {
            BusinessResult businessResult;
            if (ModelState.IsValid)
            {
                businessResult = _personBusinessService.Update(person);
                if (businessResult.Succeeded)
                {
                    TempData["Message"] = businessResult.ToBootstrapAlerts();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["Message"] = businessResult.ToBootstrapAlerts();
                }
            }
            return View(person);
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            var person = _personBusinessService.GetById(id);
            return View(person);
        }


        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var person =  _personBusinessService.GetById(id);
            return View(person);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(Guid id, Person person)
        {
            BusinessResult businessResult;
            businessResult = _personBusinessService.Delete(person);

            if (businessResult.Succeeded)
            {
                TempData["Message"] = businessResult.ToBootstrapAlerts();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["Message"] = businessResult.ToBootstrapAlerts();
            }

            return View(person);
        }
    }
}

CompanyName/CompanyName.AppName.Web/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompanyName.AppName.Business;
using CompanyName.AppName.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace CompanyName.AppName.Web.Controllers
{
    public class StateController : GenericReferentielController<State, Guid>
    {
        public StateController(ReferentielBusinessService<State, Guid> referentielBusinessService): base(referentielBusinessService)
        {

        }
    }
}

CompanyName/CompanyName.AppName.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyName.AppName.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
</head>
<body>

  
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanyName.AppName.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@menuLocalizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">@menuLocalizer["Person"]</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                @menuLocalizer["Referentiels"]
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Activity">
                                    @menuLocalizer["Activities"]
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="City" asp-action="Index">@menuLocalizer["Cities"]</a>
                                <a class="dropdown-item" asp-area="" asp-controller="State" asp-action="Index">@menuLocalizer["States"]</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@menuLocalizer["Privacy"]</a>
                        </li>
                        <partial name="_selectLanguageDropDownList" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CompanyName.AppName.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">@menuLocalizer["Privacy"]</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CompanyName/CompanyName.AppName.Web/Views/Shared/_Message.cshtml
@*THIS PARTIAL VIEW IS USED TO DISPLAY BOOTSTRAP ALERTS WHEN AN ACTION IS A COMPLETED
    ITS MESSAGE SOURCE IS THE STATIC MEMBER BusinessResultExtensions.cs/ToBootstrapAlerts()*@
@if (ViewData["Message"] != null)
    @Html.Raw(ViewData["Message"])

@if (TempData["Message"] != null)
    @Html.Raw(TempData["Message"])

CompanyName/CompanyName.AppName.Web/Views/Shared/_datatablesScript.cshtml
<script src="~/js/datatables.min.js"></script>

CompanyName/CompanyName.AppName.Web/Views/Shared/_datatablesStyle.cshtml
<link href="~/css/datatables.min.css" rel="stylesheet" />

CompanyName/CompanyName.AppName.Web/Views/Shared/_fontawesome.cshtml
<link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />

CompanyName/CompanyName.AppName.Web/Views/Shared/_select2Script.cshtml
<script src="~/lib/select2/js/select2.min.js"></script>

CompanyName/CompanyName.AppName.Web/Views/Shared/_select2Style.cshtml
<link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />

CompanyName/CompanyName.AppName.Web/Views/Shared/_selectLanguageDropDownList.cshtml
@*THIS PARTIALVIEW GET THE SUPPORTED CULTURES OF THE APP AND DISPLAYS THEM IN A DROPDOWN LIST TO BE USED BY THE USER*@


@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<partial name="_selectLanguageDropDownListStyle" />
<li id="select-language-dropdown-container">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" method="post" role="form">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</li>

CompanyName/CompanyName.AppName.Web/Views/Shared/_selectLanguageDropDownListStyle.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<link href="~/css/select-language-dropdown.css" rel="stylesheet" asp-append-version="true"/>